2023-02-09 16:00:03,998 INFO    MainThread:71001 [wandb_setup.py:_flush():68] Configure stats pid to 71001
2023-02-09 16:00:03,999 INFO    MainThread:71001 [wandb_setup.py:_flush():68] Loading settings from /home/techtoker/.config/wandb/settings
2023-02-09 16:00:03,999 INFO    MainThread:71001 [wandb_setup.py:_flush():68] Loading settings from /home/techtoker/projects/yandex_sdc/shifts-main/sdc/wandb/settings
2023-02-09 16:00:03,999 INFO    MainThread:71001 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-02-09 16:00:03,999 INFO    MainThread:71001 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'run.py', 'program': '/home/techtoker/projects/yandex_sdc/shifts-main/sdc/run.py'}
2023-02-09 16:00:03,999 INFO    MainThread:71001 [wandb_init.py:_log_setup():478] Logging user logs to ./wandb/run-20230209_160003-2n1ww40v/logs/debug.log
2023-02-09 16:00:03,999 INFO    MainThread:71001 [wandb_init.py:_log_setup():479] Logging internal logs to ./wandb/run-20230209_160003-2n1ww40v/logs/debug-internal.log
2023-02-09 16:00:03,999 INFO    MainThread:71001 [wandb_init.py:init():518] calling init triggers
2023-02-09 16:00:04,000 INFO    MainThread:71001 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-02-09 16:00:04,000 INFO    MainThread:71001 [wandb_init.py:init():571] starting backend
2023-02-09 16:00:04,000 INFO    MainThread:71001 [wandb_init.py:init():575] setting up manager
2023-02-09 16:00:04,009 INFO    MainThread:71001 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-02-09 16:00:04,013 INFO    MainThread:71001 [wandb_init.py:init():582] backend started and connected
2023-02-09 16:00:04,021 INFO    MainThread:71001 [wandb_init.py:init():670] updated telemetry
2023-02-09 16:00:04,022 INFO    MainThread:71001 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-02-09 16:00:07,172 WARNING MsgRouterThr:71001 [router.py:message_loop():77] message_loop has been closed
2023-02-09 16:00:14,061 ERROR   MainThread:71001 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/home/techtoker/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/home/techtoker/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 713, in init
    result = run_init_handle.wait(
  File "/home/techtoker/.local/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 271, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
